#name of our spring application
spring.application.name=sales-tracker

#tells spring to use an H2 database stored in a FILE. using "file" is important because we want the products to still exist after the application is restored.
spring.datasource.url=jdbc:h2:file:./data/salestrackerdb

#tells spring which database driver we are using
spring.datasource.driver-class-name=org.h2.Driver

#automatically creates/updates the database tables based on our @entity classes such as product
spring.jpa.hibernate.ddl-auto=update
